apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adofai-gg
  name: opengraph-staging
  labels:
    app: opengraph-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opengraph-staging
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: opengraph-staging
    spec:
      containers:
        - name: opengraph-staging
          image: ghcr.io/adofai-gg/opengraph:staging
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: opengraph-staging-secrets
                  name: apiEndpoint
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: opengraph-staging-secrets
                  name: s3Endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: opengraph-staging-secrets
                  name: s3AccessKey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: opengraph-staging-secrets
                  name: s3SecretKey
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: opengraph-staging-secrets
                  name: s3Bucket
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              port: 5000
              path: /
      imagePullSecrets:
        - name: registry-credentials
